INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (1, 'US States Polygon', 'US_States_Polygon_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (2, 'US States', 'US_States_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (3, 'Alabama Counties', 'Alabama_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (4, 'Alaska Counties', 'Alaska_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (5, 'Arizona Counties', 'Arizona_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (6, 'Arkansas Counties', 'Arkansas_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (7, 'California Counties', 'California_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (8, 'Colorado Counties', 'Colorado_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (9, 'Connecticut Counties', 'Connecticut_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (10, 'Delaware Counties', 'Delaware_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (11, 'Florida Counties', 'Florida_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (12, 'Georgia Counties', 'Georgia_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (13, 'Hawaii Counties', 'Hawaii_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (14, 'Idaho Counties', 'Idaho_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (15, 'Illinois Counties', 'Illinois_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (16, 'Indiana Counties', 'Indiana_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (17, 'Iowa Counties', 'Iowa_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (18, 'Kansas Counties', 'Kansas_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (19, 'Kentucky Counties', 'Kentucky_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (20, 'Louisiana Counties', 'Louisiana_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (21, 'Maine Counties', 'Maine_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (22, 'Maryland Counties', 'Maryland_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (23, 'Massachusetts Counties', 'Massachusetts_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (24, 'Michigan Counties', 'Michigan_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (25, 'Minnesota Counties', 'Minnesota_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (26, 'Mississippi Counties', 'Mississippi_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (27, 'Missouri Counties', 'Missouri_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (28, 'Montana Counties', 'Montana_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (29, 'Nebraska Counties', 'Nebraska_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (30, 'Nevada Counties', 'Nevada_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (31, 'New Hampshire Counties', 'New_Hampshire_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (32, 'New Jersey Counties', 'New_Jersey_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (33, 'New Mexico Counties', 'New_Mexico_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (34, 'New York Counties', 'New_York_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (35, 'North Carolina Counties', 'North_Carolina_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (36, 'North Dakota Counties', 'North_Dakota_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (37, 'Ohio Counties', 'Ohio_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (38, 'Oklahoma Counties', 'Oklahoma_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (39, 'Oregon Counties', 'Oregon_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (40, 'Pennsylvania Counties', 'Pennsylvania_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (41, 'Rhode Island Counties', 'Rhode_Island_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (42, 'South Carolina Counties', 'South_Carolina_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (43, 'South Dakota Counties', 'South_Dakota_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (44, 'Tennessee Counties', 'Tennessee_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (45, 'Texas Counties', 'Texas_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (46, 'Utah Counties', 'Utah_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (47, 'Vermont Counties', 'Vermont_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (48, 'Virginia Counties', 'Virginia_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (49, 'Washington Counties', 'Washington_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (50, 'West Virginia Counties', 'West_Virginia_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (51, 'Wisconsin Counties', 'Wisconsin_Counties_Thumbnail.png');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`) VALUES (52, 'Wyoming Counties', 'Wyoming_Counties_Thumbnail.png');

