INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (1, 'US States Polygon', 'US_States_Polygon_Thumbnail.png', '0,0,0');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (2, 'US States', 'US_States_Thumbnail.png', '10,49,97');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (3, 'Alabama Counties', 'Alabama_Counties_Thumbnail.png', '178,0,27');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (4, 'Alaska Counties', 'Alaska_Counties_Thumbnail.png', '254,182,24');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (5, 'Arizona Counties', 'Arizona_Counties_Thumbnail.png', '0,33,100');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (6, 'Arkansas Counties', 'Arkansas_Counties_Thumbnail.png', '0,35,104');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (7, 'California Counties', 'California_Counties_Thumbnail.png', '183,18,52');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (8, 'Colorado Counties', 'Colorado_Counties_Thumbnail.png', '0,35,104');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (9, 'Connecticut Counties', 'Connecticut_Counties_Thumbnail.png', '177,0,177');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (10, 'Delaware Counties', 'Delaware_Counties_Thumbnail.png', '231,200,52');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (11, 'Florida Counties', 'Florida_Counties_Thumbnail.png', '169,1,49');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (12, 'Georgia Counties', 'Georgia_Counties_Thumbnail.png', '182,0,34');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (13, 'Hawaii Counties', 'Hawaii_Counties_Thumbnail.png', '1,33,105');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (14, 'Idaho Counties', 'Idaho_Counties_Thumbnail.png', '239,0,57');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (15, 'Illinois Counties', 'Illinois_Counties_Thumbnail.png', '65,138,65');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (16, 'Indiana Counties', 'Indiana_Counties_Thumbnail.png', '255,185,0');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (17, 'Iowa Counties', 'Iowa_Counties_Thumbnail.png', '91,15,0');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (18, 'Kansas Counties', 'Kansas_Counties_Thumbnail.png', '77,145,198');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (19, 'Kentucky Counties', 'Kentucky_Counties_Thumbnail.png', '45,147,125');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (20, 'Louisiana Counties', 'Louisiana_Counties_Thumbnail.png', '234,164,95');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (21, 'Maine Counties', 'Maine_Counties_Thumbnail.png', '196,0,29');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (22, 'Maryland Counties', 'Maryland_Counties_Thumbnail.png', '0,0,0');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (23, 'Massachusetts Counties', 'Massachusetts_Counties_Thumbnail.png', '32,44,92');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (24, 'Michigan Counties', 'Michigan_Counties_Thumbnail.png', '239,20,57');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (25, 'Minnesota Counties', 'Minnesota_Counties_Thumbnail.png', '60,157,189');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (26, 'Mississippi Counties', 'Mississippi_Counties_Thumbnail.png', '214,154,45');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (27, 'Missouri Counties', 'Missouri_Counties_Thumbnail.png', '0,75,142');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (28, 'Montana Counties', 'Montana_Counties_Thumbnail.png', '162,209,0');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (29, 'Nebraska Counties', 'Nebraska_Counties_Thumbnail.png', '207,207,207');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (30, 'Nevada Counties', 'Nevada_Counties_Thumbnail.png', '255,163,0');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (31, 'New Hampshire Counties', 'New_Hampshire_Counties_Thumbnail.png', '63,134,63');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (32, 'New Jersey Counties', 'New_Jersey_Counties_Thumbnail.png', '16,138,224');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (33, 'New Mexico Counties', 'New_Mexico_Counties_Thumbnail.png', '252,224,32');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (34, 'New York Counties', 'New_York_Counties_Thumbnail.png', '108,44,19');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (35, 'North Carolina Counties', 'North_Carolina_Counties_Thumbnail.png', '255,202,0');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (36, 'North Dakota Counties', 'North_Dakota_Counties_Thumbnail.png', '120,100,69');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (37, 'Ohio Counties', 'Ohio_Counties_Thumbnail.png', '194,11,58');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (38, 'Oklahoma Counties', 'Oklahoma_Counties_Thumbnail.png', '160,49,12');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (39, 'Oregon Counties', 'Oregon_Counties_Thumbnail.png', '255,234,15');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (40, 'Pennsylvania Counties', 'Pennsylvania_Counties_Thumbnail.png', '255,206,0');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (41, 'Rhode Island Counties', 'Rhode_Island_Counties_Thumbnail.png', '0,50,113');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (42, 'South Carolina Counties', 'South_Carolina_Counties_Thumbnail.png', '255,255,255');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (43, 'South Dakota Counties', 'South_Dakota_Counties_Thumbnail.png', '255,196,0');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (44, 'Tennessee Counties', 'Tennessee_Counties_Thumbnail.png', '0,45,101');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (45, 'Texas Counties', 'Texas_Counties_Thumbnail.png', '192,5,60');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (46, 'Utah Counties', 'Utah_Counties_Thumbnail.png', '255,184,29');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (47, 'Vermont Counties', 'Vermont_Counties_Thumbnail.png', '194,75,32');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (48, 'Virginia Counties', 'Virginia_Counties_Thumbnail.png', '222,24,36');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (49, 'Washington Counties', 'Washington_Counties_Thumbnail.png', '255,213,32');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (50, 'West Virginia Counties', 'West_Virginia_Counties_Thumbnail.png', '10,49,97');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (51, 'Wisconsin Counties', 'Wisconsin_Counties_Thumbnail.png', '119,166,198');
INSERT INTO `map` (`map_id`, `map_name`, `map_thumbnail`, `map_primary_color`) VALUES (52, 'Wyoming Counties', 'Wyoming_Counties_Thumbnail.png', '191,10,48');

