INSERT INTO `map` (`map_id`, `map_scale`, `map_name`, `map_thumbnail`, `map_primary_color_R`, `map_primary_color_G`, `map_primary_color_B`, `map_is_custom`) VALUES (27, 145.994200, 'Mississippi Counties', 'Mississippi_Counties_Thumbnail.png', 214,154,45, 0);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1576, "Mississippi", 3.289464, 0.000522);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1564, "Mississippi", 2.918544, 0.299088);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1507, "Mississippi", 2.831469, 0.000000);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1575, "Mississippi", 2.566418, 0.000229);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1510, "Mississippi", 2.302104, 0.001369);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1552, "Mississippi", 1.930684, 0.000949);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1522, "Mississippi", 1.337266, 0.000448);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1574, "Mississippi", 1.410727, 0.278974);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1577, "Mississippi", 1.063414, 0.130396);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1565, "Mississippi", 1.204027, 0.606204);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1519, "Mississippi", 0.693965, 0.589276);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1559, "Mississippi", 1.456377, 0.552034);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1541, "Mississippi", 1.933666, 0.551889);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1578, "Mississippi", 2.408669, 0.496784);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1546, "Mississippi", 2.829474, 0.608269);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1534, "Mississippi", 3.110364, 0.663470);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1563, "Mississippi", 2.408669, 0.769813);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1512, "Mississippi", 2.145259, 1.042462);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1514, "Mississippi", 2.463228, 1.151380);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1553, "Mississippi", 2.934809, 1.133389);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1518, "Mississippi", 2.618988, 1.479597);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1558, "Mississippi", 2.566349, 1.788528);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1549, "Mississippi", 2.983758, 1.563077);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1515, "Mississippi", 2.200958, 1.828561);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1583, "Mississippi", 2.147873, 1.570778);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1527, "Mississippi", 1.517998, 1.372618);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1573, "Mississippi", 1.203366, 1.039687);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1586, "Mississippi", 1.723524, 1.004383);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1572, "Mississippi", 0.890565, 1.260582);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1511, "Mississippi", 0.420677, 1.094174);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1581, "Mississippi", 0.421179, 1.832311);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1533, "Mississippi", 0.440981, 2.480914);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1568, "Mississippi", 0.690143, 2.373293);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1580, "Mississippi", 0.480457, 2.971492);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1530, "Mississippi", 0.926386, 3.027836);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1587, "Mississippi", 0.895254, 2.467084);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1532, "Mississippi", 0.921792, 2.083208);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1547, "Mississippi", 1.201207, 1.480827);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1531, "Mississippi", 1.223058, 2.026163);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1513, "Mississippi", 1.480252, 1.648870);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1554, "Mississippi", 1.868119, 1.648058);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1509, "Mississippi", 1.689126, 2.137637);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1550, "Mississippi", 1.203611, 2.638306);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1566, "Mississippi", 1.406586, 3.003447);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1545, "Mississippi", 1.924704, 2.580498);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1567, "Mississippi", 1.870884, 2.952279);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1555, "Mississippi", 2.335845, 2.580498);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1585, "Mississippi", 2.335845, 2.137035);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1557, "Mississippi", 2.841400, 2.134666);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1540, "Mississippi", 2.739772, 2.583719);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1543, "Mississippi", 2.739567, 3.022412);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1556, "Mississippi", 2.332316, 3.023871);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1570, "Mississippi", 1.923931, 3.465368);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1536, "Mississippi", 2.332316, 3.464832);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1517, "Mississippi", 2.741161, 3.460497);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1569, "Mississippi", 1.407088, 3.682905);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1520, "Mississippi", 0.918183, 3.682530);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1516, "Mississippi", 0.406865, 3.463667);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1537, "Mississippi", 0.290324, 3.907755);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1524, "Mississippi", 0.496859, 4.230579);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1548, "Mississippi", 0.917679, 4.098158);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1544, "Mississippi", 1.409816, 4.042997);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1538, "Mississippi", 1.678956, 4.026747);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1521, "Mississippi", 1.899393, 3.998986);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1539, "Mississippi", 2.253780, 3.964358);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1582, "Mississippi", 2.711540, 3.877744);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1526, "Mississippi", 2.813302, 4.450270);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1561, "Mississippi", 2.508831, 4.452500);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1523, "Mississippi", 2.203391, 4.452377);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1542, "Mississippi", 2.000796, 4.452529);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1551, "Mississippi", 1.614523, 4.452449);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1579, "Mississippi", 1.394537, 4.556479);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1562, "Mississippi", 1.106622, 4.557222);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1508, "Mississippi", 0.559609, 4.558097);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1584, "Mississippi", 0.018065, 4.528603);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1506, "Mississippi", 0.000000, 4.063421);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1525, "Mississippi", 2.769969, 4.996993);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1535, "Mississippi", 2.770473, 5.325567);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1529, "Mississippi", 2.313294, 5.398449);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1528, "Mississippi", 1.965229, 5.434597);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1560, "Mississippi", 1.802745, 4.975033);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (27, 1571, "Mississippi", 2.313562, 5.106579);

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1218, "Louisiana", -0.977152, 5.643586, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1219, "Louisiana", -1.47618, 5.121457, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1220, "Louisiana", 0.548448, 5.811397, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1222, "Louisiana", -0.62573, 4.566303, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1223, "Louisiana", -2.085245, 5.140576, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1224, "Louisiana", -1.773636, 3.013482, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1225, "Louisiana", -2.18759, 2.470744, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1226, "Louisiana", -2.388138, 2.470848, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1227, "Louisiana", -2.110815, 5.631909, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1228, "Louisiana", -0.657509, 3.398378, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1230, "Louisiana", -0.368507, 3.780452, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1231, "Louisiana", -1.583639, 2.472072, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1232, "Louisiana", -0.212415, 4.042735, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1233, "Louisiana", -2.387745, 3.314143, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1234, "Louisiana", 0.339726, 5.345742, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1235, "Louisiana", 0.197394, 2.48871, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1236, "Louisiana", 0.334302, 4.995525, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1237, "Louisiana", -0.977016, 4.994597, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1238, "Louisiana", -0.278221, 3.237854, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1239, "Louisiana", -1.318521, 3.998453, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1240, "Louisiana", -0.375179, 6.092047, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1241, "Louisiana", -0.046331, 5.62288, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1242, "Louisiana", -1.16214, 3.124554, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1243, "Louisiana", 1.374727, 6.008048, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1244, "Louisiana", -1.476216, 5.634577, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1245, "Louisiana", -0.629668, 5.771323, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1247, "Louisiana", -0.729434, 3.835352, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1248, "Louisiana", -1.225917, 2.795762, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1249, "Louisiana", 0.665116, 5.432546, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1250, "Louisiana", 0.097724, 3.041882, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1251, "Louisiana", -0.430608, 2.484862, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1252, "Louisiana", -1.78668, 3.559428, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1253, "Louisiana", 1.514933, 5.996738, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1254, "Louisiana", -0.760568, 2.841311, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1256, "Louisiana", -0.168064, 4.971548, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1257, "Louisiana", -1.326452, 4.348219, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1258, "Louisiana", -1.959682, 3.448157, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1259, "Louisiana", -0.379465, 2.910941, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1260, "Louisiana", -2.224286, 3.938522, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1261, "Louisiana", 1.642905, 6.042863, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1262, "Louisiana", 1.105267, 6.040801, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1263, "Louisiana", 0.744307, 4.995398, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1264, "Louisiana", 0.691264, 6.037004, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1265, "Louisiana", 0.966159, 5.871333, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1266, "Louisiana", -0.838252, 5.182609, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1267, "Louisiana", -0.33371, 5.622398, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1269, "Louisiana", 1.397472, 5.354508, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1270, "Louisiana", 1.087809, 4.994615, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1271, "Louisiana", 0.077355, 3.433391, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1273, "Louisiana", -1.079039, 2.477067, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1274, "Louisiana", -1.082209, 6.058285, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1275, "Louisiana", -1.916898, 4.539451, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1276, "Louisiana", 1.307704, 4.989025, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1277, "Louisiana", -1.875398, 2.471793, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1278, "Louisiana", 0.169854, 5.421718, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1279, "Louisiana", 0.016125, 2.48744, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1280, "Louisiana", -0.09511, 4.939746, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 1281, "Louisiana", -1.321028, 3.560164, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2247, "Oklahoma", -4.33657, 1.048858, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2266, "Oklahoma", -3.800182, -0.578553, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2274, "Oklahoma", -3.859468, -0.078087, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2275, "Oklahoma", -3.404949, -0.489174, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2280, "Oklahoma", -3.501729, 0.610743, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2296, "Oklahoma", -4.437035, -0.379802, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2299, "Oklahoma", -4.124367, 0.394074, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 427, "Florida", 5.659077, 5.535603, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 431, "Florida", 6.265327, 5.485031, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 440, "Florida", 4.020065, 4.996318, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 443, "Florida", 6.722491, 5.355637, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 446, "Florida", 6.23301, 5.99339, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 453, "Florida", 5.617416, 4.998903, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 455, "Florida", 6.055076, 4.993956, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 460, "Florida", 6.939863, 5.38843, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 462, "Florida", 6.500994, 5.487071, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 470, "Florida", 4.855817, 4.998878, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 481, "Florida", 4.341398, 4.995606, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 489, "Florida", 6.917162, 5.865697, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 490, "Florida", 5.257646, 5.00199, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 491, "Florida", 5.661412, 5.206873, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2628, "Texas", -4.409851, 3.639471, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2630, "Texas", -3.350518, 4.336418, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2646, "Texas", -3.091918, 1.609793, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2659, "Texas", -3.497197, 2.400415, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2661, "Texas", -2.998986, 2.106013, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2664, "Texas", -3.804901, 3.572577, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2687, "Texas", -4.20677, 1.875831, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2707, "Texas", -3.653949, 2.008247, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2719, "Texas", -3.331926, 2.91068, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2727, "Texas", -3.077723, 5.586306, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2728, "Texas", -4.305726, 6.031937, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2729, "Texas", -3.047187, 2.753705, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2734, "Texas", -4.797363, 3.296669, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2739, "Texas", -4.208287, 2.023577, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2740, "Texas", -4.12057, 4.253957, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2748, "Texas", -2.802808, 4.797475, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2750, "Texas", -2.789902, 6.008682, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2766, "Texas", -4.202729, 1.326963, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2773, "Texas", -3.51089, 5.628122, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2785, "Texas", -3.050871, 2.643702, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2797, "Texas", -4.175231, 5.45721, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2799, "Texas", -3.16482, 2.038372, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2801, "Texas", -3.32175, 3.93812, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2803, "Texas", -2.256117, 4.761812, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2808, "Texas", -2.462596, 5.939834, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2810, "Texas", -2.946553, 3.252392, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2814, "Texas", -3.545171, 4.811841, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2821, "Texas", -3.655665, 1.292621, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2828, "Texas", -3.330723, 3.235559, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2829, "Texas", -2.393676, 4.230268, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2830, "Texas", -2.744083, 4.178069, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2831, "Texas", -3.704148, 5.113772, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2837, "Texas", -2.856423, 3.767978, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2839, "Texas", -3.939533, 2.886282, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2852, "Texas", -3.471121, 1.998099, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2855, "Texas", -3.779773, 4.511401, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2856, "Texas", -3.002984, 4.921373, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2857, "Texas", -3.498403, 2.614437, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2861, "Texas", -4.421794, 2.696953, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2863, "Texas", -4.208051, 4.922442, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2877, "Texas", -4.010382, 2.478253, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2538, "Tennessee", 6.629446, -0.452275, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2556, "Tennessee", 2.010959, -0.5109, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2558, "Tennessee", 5.321655, -0.458194, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2560, "Tennessee", 4.422568, -0.57496, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2565, "Tennessee", 6.180902, -0.577442, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2567, "Tennessee", 2.456719, -0.545957, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2568, "Tennessee", 3.274499, -0.534015, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2582, "Tennessee", 4.043083, -0.577242, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2584, "Tennessee", 4.8187, -0.468453, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2590, "Tennessee", 5.781984, -0.404051, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2587, "Tennessee", 2.868208, -0.485794, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2602, "Tennessee", 6.879157, -0.361776, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2611, "Tennessee", 1.345296, -0.516789, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 2623, "Tennessee", 3.630268, -0.619549, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 495, "Georgia", 7.013337, 4.426635, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 499, "Georgia", 6.607964, 0.728854, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 510, "Georgia", 6.835202, 4.190477, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 513, "Georgia", 6.316765, 1.47966, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 514, "Georgia", 6.389953, 0.010506, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 517, "Georgia", 6.64691, 3.076496, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 518, "Georgia", 6.127732, 0.508084, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 519, "Georgia", 6.995765, 0.729327, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 521, "Georgia", 6.521168, 4.019625, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 522, "Georgia", 7.196079, 1.683981, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 524, "Georgia", 6.91543, 1.142872, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 529, "Georgia", 6.639651, 1.855464, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 530, "Georgia", 7.45238, 2.673645, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 532, "Georgia", 6.049843, 0.014217, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 533, "Georgia", 7.309348, 0.472657, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 534, "Georgia", 6.77946, 4.895868, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 535, "Georgia", 7.304861, 1.281462, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 538, "Georgia", 7.198133, 4.182223, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 539, "Georgia", 6.744134, 1.48708, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 540, "Georgia", 6.540459, 4.346726, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 546, "Georgia", 7.032257, 0.009554, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 547, "Georgia", 7.028248, 1.806397, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 548, "Georgia", 6.192902, 0.510711, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 549, "Georgia", 7.395987, 0.82612, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 551, "Georgia", 6.804295, 1.012324, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 552, "Georgia", 6.997908, 0.173245, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 555, "Georgia", 6.542682, 0.452405, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 556, "Georgia", 7.274303, 4.89646, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 558, "Georgia", 7.377916, 1.034387, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 562, "Georgia", 6.268497, 1.362186, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 563, "Georgia", 6.469217, 2.654446, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 565, "Georgia", 6.361055, 1.959976, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 566, "Georgia", 7.300607, 1.68593, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 576, "Georgia", 7.384867, 2.241534, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 579, "Georgia", 7.316763, 3.849827, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 584, "Georgia", 7.46397, 0.31899, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 587, "Georgia", 7.399094, 3.08181, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 589, "Georgia", 6.996087, 3.04246, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 590, "Georgia", 6.790483, 2.206677, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 591, "Georgia", 6.732585, 4.670804, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 592, "Georgia", 7.146932, 4.440372, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 596, "Georgia", 6.721286, 0.009653, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 597, "Georgia", 6.575325, 2.984944, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 601, "Georgia", 6.6047, 1.141848, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 603, "Georgia", 7.00064, 0.540703, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 605, "Georgia", 7.119833, 2.233952, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 606, "Georgia", 6.233126, 1.119229, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 609, "Georgia", 6.513177, 3.755242, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 611, "Georgia", 6.695683, 3.830655, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 613, "Georgia", 7.470867, 1.512495, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 614, "Georgia", 7.224789, 3.210006, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 616, "Georgia", 6.631432, 4.900685, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 617, "Georgia", 7.147057, 2.054287, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 619, "Georgia", 6.591812, 3.453873, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 620, "Georgia", 7.2112, 3.457936, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 621, "Georgia", 6.95181, 2.642827, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 624, "Georgia", 7.201852, 2.810532, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 626, "Georgia", 7.051922, 3.785744, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 632, "Georgia", 6.41844, 2.214197, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 635, "Georgia", 7.475921, 0.010684, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 636, "Georgia", 7.123039, 2.49575, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 637, "Georgia", 6.120906, 0.01372, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 643, "Georgia", 6.99919, 3.453746, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 646, "Georgia", 6.486561, 0.010059, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 215, "Arkansas", -0.056668, 0.535002, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 216, "Arkansas", -0.483682, 1.997198, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 220, "Arkansas", -0.725479, 1.610382, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 221, "Arkansas", -1.121687, 1.492189, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 223, "Arkansas", 0.194631, 1.790471, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 224, "Arkansas", -1.847201, 0.819015, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 227, "Arkansas", -0.820638, 1.164861, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 228, "Arkansas", -1.835549, 1.926213, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 232, "Arkansas", 1.148482, -0.556994, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 234, "Arkansas", -1.30611, 1.050441, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 235, "Arkansas", 0.097351, 1.096265, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 236, "Arkansas", -0.360116, 1.504757, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 237, "Arkansas", -0.944081, -0.465458, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 240, "Arkansas", -1.752196, 0.278511, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 241, "Arkansas", -1.023374, 0.625431, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 243, "Arkansas", -2.314642, 1.233947, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 244, "Arkansas", -1.753171, 0.612397, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 245, "Arkansas", -2.601253, 0.800323, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 249, "Arkansas", -0.578294, 0.629051, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 251, "Arkansas", -2.205262, 1.892527, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 253, "Arkansas", 0.552571, 0.10509, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 254, "Arkansas", -0.321431, 1.027019, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 255, "Arkansas", -2.830867, 1.314626, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 256, "Arkansas", -2.486757, -0.542092, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 257, "Arkansas", -0.466532, -0.100332, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 260, "Arkansas", -2.388424, 1.73183, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 262, "Arkansas", 0.20712, -0.010298, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 263, "Arkansas", -2.280427, 0.311807, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 264, "Arkansas", -1.828924, 1.298146, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 266, "Arkansas", -1.463944, 1.46802, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 267, "Arkansas", -1.650856, -0.148498, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 268, "Arkansas", 0.537091, 0.437918, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 269, "Arkansas", -2.282001, 0.807272, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 271, "Arkansas", -2.815275, 0.333877, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 273, "Arkansas", -0.148427, -0.119416, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 274, "Arkansas", -1.100392, -0.02318, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 277, "Arkansas", -1.420171, 0.171623, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 278, "Arkansas", -2.79957, -0.129744, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 280, "Arkansas", -2.792875, -0.567884, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 281, "Arkansas", -2.822313, 1.004438, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 276, "Arkansas", 0.50251, -0.191333, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 284, "Arkansas", -1.333769, 2.01049, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 287, "Arkansas", -0.46474, -0.672534, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 288, "Arkansas", 0.176756, -0.562159, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 289, "Arkansas", -2.054977, -0.395481, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 103, "Alabama", 4.733811, 2.860831, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 104, "Alabama", 3.625736, 4.596293, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 105, "Alabama", 5.906757, 3.559751, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 106, "Alabama", 4.233071, 2.186431, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 107, "Alabama", 4.69165, 0.919833, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 108, "Alabama", 5.655849, 3.363547, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 109, "Alabama", 4.74607, 3.789278, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 110, "Alabama", 5.508781, 1.284489, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 111, "Alabama", 6.06137, 2.358774, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 112, "Alabama", 5.811208, 0.587315, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 113, "Alabama", 4.635851, 2.405236, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 114, "Alabama", 3.18178, 3.356846, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 115, "Alabama", 3.475706, 3.755871, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 116, "Alabama", 5.480638, 1.871636, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 117, "Alabama", 5.767332, 1.289905, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 118, "Alabama", 5.458643, 4.221357, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 119, "Alabama", 3.515019, 0.111798, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 120, "Alabama", 4.227553, 4.053771, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 121, "Alabama", 5.132725, 2.364205, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 122, "Alabama", 4.952215, 4.334427, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 123, "Alabama", 5.151261, 3.680485, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 124, "Alabama", 4.50397, 0.852817, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 125, "Alabama", 5.863605, 4.219357, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 126, "Alabama", 4.181928, 2.833148, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 127, "Alabama", 5.536179, 0.169601, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 128, "Alabama", 5.241672, 2.783657, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 129, "Alabama", 4.039119, 4.667579, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 130, "Alabama", 5.284856, 0.994119, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 131, "Alabama", 3.70319, 1.34515, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 132, "Alabama", 3.481376, 0.517935, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 133, "Alabama", 5.461531, 4.745207, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 134, "Alabama", 3.447693, 2.303017, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 135, "Alabama", 3.786166, 2.486534, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 136, "Alabama", 6.237273, 4.02773, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 137, "Alabama", 5.944673, 4.601348, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 138, "Alabama", 5.295972, 0.006191, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 139, "Alabama", 4.313308, 1.441017, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 140, "Alabama", 3.380389, 1.172147, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 141, "Alabama", 3.45205, -0.014971, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 142, "Alabama", 4.124316, 0.239568, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 143, "Alabama", 5.958253, 2.805378, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 144, "Alabama", 4.376523, -0.003715, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 145, "Alabama", 4.746673, 3.237917, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 146, "Alabama", 5.631997, 3.000147, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 147, "Alabama", 4.864951, 0.004977, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 148, "Alabama", 3.536664, 3.061705, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 149, "Alabama", 3.44778, 0.843747, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 150, "Alabama", 5.073073, 0.49499, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 151, "Alabama", 3.223001, 4.778432, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 152, "Alabama", 3.870631, 3.955792, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 153, "Alabama", 5.158234, 3.117951, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 154, "Alabama", 4.544895, 0.387518, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 155, "Alabama", 4.129655, 2.651158, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 156, "Alabama", 3.314576, 1.827554, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 157, "Alabama", 5.455598, 3.667877, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 158, "Alabama", 6.001352, 1.870679, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 159, "Alabama", 6.220965, 3.107436, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 161, "Alabama", 4.628163, 1.812473, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 160, "Alabama", 5.077207, 1.258311, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 162, "Alabama", 3.233555, 2.500239, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 163, "Alabama", 5.151881, 1.62426, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 164, "Alabama", 5.645836, 2.360888, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 165, "Alabama", 3.814325, 1.732772, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 166, "Alabama", 4.018891, 1.238489, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 167, "Alabama", 3.190581, 4.120936, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 168, "Alabama", 3.987063, 3.408954, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (27, 169, "Alabama", 4.018445, 0.861317, "outside");
