INSERT INTO `map` (`map_id`, `map_scale`, `map_name`, `map_thumbnail`, `map_primary_color_R`, `map_primary_color_G`, `map_primary_color_B`, `map_is_custom`) VALUES (49, 187.360393, 'Virginia Counties & Independent Cities', 'Virginia_Counties_and_Independent_Cities_Thumbnail.png', 222,24,36, 0);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2995, "Virginia", 4.982983, 2.585048);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2928, "Virginia", 5.434665, 2.459950);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2989, "Virginia", 5.436062, 2.712241);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3054, "Virginia", 7.447354, 3.167582);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3024, "Virginia", 7.183932, 3.249580);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3047, "Virginia", 7.255044, 3.178456);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3043, "Virginia", 7.338630, 3.121582);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3053, "Virginia", 6.744478, 3.171370);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2970, "Virginia", 6.750786, 2.904940);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3008, "Virginia", 6.173496, 3.087251);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3031, "Virginia", 6.707388, 3.447853);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2964, "Virginia", 5.908289, 3.211410);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3028, "Virginia", 6.114339, 3.433153);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3012, "Virginia", 6.056384, 2.942472);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3011, "Virginia", 6.519999, 2.771889);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3042, "Virginia", 7.050632, 2.806842);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3034, "Virginia", 7.224932, 2.940601);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3019, "Virginia", 6.919903, 2.607342);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3046, "Virginia", 7.262531, 2.869197);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2987, "Virginia", 7.649659, 2.385934);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2925, "Virginia", 7.628882, 1.798730);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2981, "Virginia", 7.223758, 2.413088);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2960, "Virginia", 6.963109, 2.328548);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2971, "Virginia", 6.765768, 2.498671);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2972, "Virginia", 6.488998, 1.867515);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2983, "Virginia", 6.924341, 2.119693);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2975, "Virginia", 7.033136, 2.033998);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2988, "Virginia", 7.041185, 1.788997);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2952, "Virginia", 6.505775, 1.630477);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3000, "Virginia", 6.736009, 1.676961);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3016, "Virginia", 6.610745, 1.484957);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2974, "Virginia", 6.329841, 1.945375);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2986, "Virginia", 6.434427, 2.298914);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2967, "Virginia", 6.020013, 2.195142);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2943, "Virginia", 6.404739, 2.469265);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2996, "Virginia", 6.276211, 2.681570);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3045, "Virginia", 6.220827, 2.776453);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3025, "Virginia", 6.243622, 2.709329);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3036, "Virginia", 6.339747, 2.685445);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3056, "Virginia", 6.934269, 2.700107);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2945, "Virginia", 5.797859, 2.377533);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3049, "Virginia", 6.074241, 2.329453);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2966, "Virginia", 5.878601, 1.822758);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2951, "Virginia", 5.775078, 2.743919);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2937, "Virginia", 5.629202, 3.054070);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2979, "Virginia", 5.182386, 2.932404);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2982, "Virginia", 4.937616, 3.218491);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2944, "Virginia", 4.770825, 2.771567);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2965, "Virginia", 4.456961, 3.005643);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2994, "Virginia", 5.543366, 2.218176);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2961, "Virginia", 5.516089, 1.951130);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2949, "Virginia", 5.210324, 2.146855);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2939, "Virginia", 4.845076, 2.086320);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2956, "Virginia", 5.184069, 1.824423);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2926, "Virginia", 4.836540, 1.485099);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3023, "Virginia", 5.151734, 1.744379);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2978, "Virginia", 5.368651, 1.641832);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2985, "Virginia", 4.503283, 1.773303);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2929, "Virginia", 4.238469, 2.064839);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2940, "Virginia", 4.232553, 2.540419);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3038, "Virginia", 4.407032, 2.496303);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2930, "Virginia", 4.653726, 2.391838);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2934, "Virginia", 3.817010, 2.311193);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2993, "Virginia", 3.960574, 2.910698);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3027, "Virginia", 4.156419, 3.529325);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2968, "Virginia", 3.580669, 3.262342);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3041, "Virginia", 3.771336, 3.440627);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2957, "Virginia", 3.439958, 2.791604);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3001, "Virginia", 3.413230, 2.554428);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3050, "Virginia", 3.637937, 2.660873);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3051, "Virginia", 3.555075, 2.677149);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2992, "Virginia", 3.049710, 3.242353);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2942, "Virginia", 2.632988, 3.167790);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3033, "Virginia", 2.729922, 3.464102);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2962, "Virginia", 1.997881, 3.324455);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2955, "Virginia", 3.041428, 2.928889);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2984, "Virginia", 3.061121, 2.621473);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3048, "Virginia", 3.079344, 2.897674);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2998, "Virginia", 2.744788, 2.776427);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3018, "Virginia", 2.296012, 2.990829);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3007, "Virginia", 1.838317, 3.059420);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3015, "Virginia", 1.343336, 3.171216);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3021, "Virginia", 1.432734, 3.487509);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3005, "Virginia", 0.690291, 3.226716);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3017, "Virginia", 0.796774, 2.828992);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3044, "Virginia", 1.012123, 3.132927);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2950, "Virginia", 1.121548, 2.699928);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2938, "Virginia", 1.361104, 2.410268);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3004, "Virginia", 1.268782, 2.904324);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3013, "Virginia", 1.774522, 2.660407);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2935, "Virginia", 2.213137, 2.704667);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2959, "Virginia", 2.660926, 2.480424);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2947, "Virginia", 3.202617, 2.257153);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2936, "Virginia", 3.601294, 2.081299);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2927, "Virginia", 3.379275, 1.881887);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3026, "Virginia", 3.667397, 2.065564);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2933, "Virginia", 3.619085, 1.499499);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3002, "Virginia", 3.986645, 1.724948);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3037, "Virginia", 4.219745, 2.089035);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3022, "Virginia", 4.293906, 2.129898);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2932, "Virginia", 4.148093, 1.235440);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3052, "Virginia", 4.562373, 1.583743);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3055, "Virginia", 4.725137, 1.707762);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3003, "Virginia", 4.451104, 0.769887);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3035, "Virginia", 4.757879, 1.220843);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3006, "Virginia", 4.806138, 0.455070);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3014, "Virginia", 5.280708, 0.536728);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2958, "Virginia", 5.131221, 0.000000);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3057, "Virginia", 5.474915, 0.326567);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2946, "Virginia", 5.523799, 0.251738);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2991, "Virginia", 4.984103, 0.804028);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2980, "Virginia", 5.222614, 1.048375);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2999, "Virginia", 5.337240, 0.751434);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2954, "Virginia", 5.544840, 0.565349);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2948, "Virginia", 5.443611, 0.959548);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2963, "Virginia", 5.012269, 1.238107);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2990, "Virginia", 5.306432, 1.341195);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3009, "Virginia", 5.728359, 1.359882);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2941, "Virginia", 6.031955, 1.516744);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3010, "Virginia", 6.040285, 1.092200);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3032, "Virginia", 6.145130, 1.425138);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2973, "Virginia", 6.330743, 1.331830);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2997, "Virginia", 5.959526, 0.654195);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3039, "Virginia", 6.149326, 0.856125);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3040, "Virginia", 6.196300, 0.848273);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2953, "Virginia", 6.139424, 0.510272);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3030, "Virginia", 6.480704, 0.708674);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3020, "Virginia", 6.531735, 0.776669);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2931, "Virginia", 6.503137, 0.664553);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2977, "Virginia", 5.713211, 0.177276);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 3029, "Virginia", 6.340591, 0.742909);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2969, "Virginia", 3.865260, 1.093122);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (49, 2976, "Virginia", 0.000000, 3.216521);

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1103, "Kentucky", -0.302511, 1.457175, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1104, "Kentucky", -0.280819, 3.137783, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1107, "Kentucky", 0.857962, 1.200344, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1110, "Kentucky", 0.096228, 2.207795, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1119, "Kentucky", 0.334065, 1.202142, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1123, "Kentucky", -0.294158, 2.634922, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1129, "Kentucky", 0.407659, 1.498844, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1130, "Kentucky", -0.451204, 2.016183, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1132, "Kentucky", -0.307408, 1.175789, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1133, "Kentucky", 0.729541, 2.137234, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1142, "Kentucky", 0.508995, 0.886796, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1145, "Kentucky", 0.163684, 3.056122, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1155, "Kentucky", 0.670764, 1.832121, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1157, "Kentucky", 0.540705, 2.424728, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1158, "Kentucky", -0.417311, 3.013867, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1161, "Kentucky", 0.653299, 1.49883, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1162, "Kentucky", -0.230158, 2.186937, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1163, "Kentucky", 0.122313, 2.681811, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1164, "Kentucky", 0.521602, 2.743138, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1165, "Kentucky", 0.0295, 0.950905, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1174, "Kentucky", 0.404775, 1.964467, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1177, "Kentucky", 1.004601, 1.879033, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1178, "Kentucky", -0.31619, 0.872326, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1180, "Kentucky", -0.099755, 1.758912, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1185, "Kentucky", 0.168903, 1.688284, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1192, "Kentucky", -0.212881, 2.405802, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1194, "Kentucky", 0.123635, 2.528093, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1195, "Kentucky", 0.942721, 2.156304, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1196, "Kentucky", -0.351958, 1.915309, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1200, "Kentucky", 0.040219, 1.336958, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1216, "Kentucky", -0.032558, 2.005133, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2349, "Pennsylvania", 6.204331, -0.754916, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2353, "Pennsylvania", 4.867076, -1.075573, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2363, "Pennsylvania", 7.572939, -0.970673, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2369, "Pennsylvania", 6.047906, -1.07809, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2371, "Pennsylvania", 8.077501, -0.749413, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2374, "Pennsylvania", 3.666071, -0.847607, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2376, "Pennsylvania", 5.576443, -1.029766, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2377, "Pennsylvania", 5.294851, -0.873898, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2378, "Pennsylvania", 3.155992, -0.693183, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2384, "Pennsylvania", 6.953792, -1.062448, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2399, "Pennsylvania", 8.395146, -0.839974, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2404, "Pennsylvania", 4.258058, -1.023561, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2411, "Pennsylvania", 3.156197, -1.264474, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2415, "Pennsylvania", 6.53799, -0.950395, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2148, "Ohio", -0.029902, 0.513519, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2152, "Ohio", 1.37776, -0.113202, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2154, "Ohio", 2.438098, -0.883222, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2155, "Ohio", -0.377257, 0.264896, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2159, "Ohio", -0.378297, -0.717712, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2161, "Ohio", -0.332038, -0.129236, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2170, "Ohio", 0.832461, -0.593937, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2171, "Ohio", 0.005219, -0.31358, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2172, "Ohio", 0.414735, -0.846331, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2174, "Ohio", 1.092731, 0.538667, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2176, "Ohio", -0.438762, -0.480877, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2177, "Ohio", 1.946804, -0.945571, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2183, "Ohio", -0.196801, 0.109095, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2184, "Ohio", 0.926824, -0.244615, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2187, "Ohio", 0.868323, 0.322557, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2191, "Ohio", 0.859435, 0.771174, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2192, "Ohio", 0.892917, -1.01373, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2196, "Ohio", 0.022085, -0.80682, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2200, "Ohio", 1.351519, 0.325647, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2203, "Ohio", 2.35629, -0.504323, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2205, "Ohio", 1.59519, -0.381185, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2207, "Ohio", 1.441439, -0.876085, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2208, "Ohio", 1.97797, -0.609526, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2211, "Ohio", 1.203013, -0.58046, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2212, "Ohio", 0.408677, -0.433113, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2213, "Ohio", 0.289779, 0.335534, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2218, "Ohio", 0.281904, -0.062796, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2220, "Ohio", 0.404597, 0.562778, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2229, "Ohio", 0.91252, 0.087808, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2231, "Ohio", 1.822482, -0.224954, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1995, "North Carolina", 4.132986, 4.020424, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1996, "North Carolina", 2.331821, 4.275451, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1997, "North Carolina", 2.322155, 3.613736, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1999, "North Carolina", 1.935764, 3.597369, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2000, "North Carolina", 1.594467, 3.973624, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2002, "North Carolina", 6.347846, 4.024293, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2008, "North Carolina", 1.864898, 4.179242, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2009, "North Carolina", 7.133878, 3.643827, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2011, "North Carolina", 4.143548, 3.655343, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2015, "North Carolina", 6.953971, 3.893695, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2021, "North Carolina", 7.362112, 3.644074, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2022, "North Carolina", 7.661413, 4.043105, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2023, "North Carolina", 3.187997, 4.299005, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2024, "North Carolina", 2.967589, 4.254197, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2026, "North Carolina", 4.65911, 4.033365, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2027, "North Carolina", 5.846971, 4.139549, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2028, "North Carolina", 3.158733, 4.005622, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2029, "North Carolina", 5.129002, 3.999777, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2031, "North Carolina", 6.724808, 3.642399, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2033, "North Carolina", 4.867928, 3.654423, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2035, "North Carolina", 3.628544, 4.011035, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2036, "North Carolina", 5.668863, 3.692552, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2040, "North Carolina", 6.466945, 3.649634, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2043, "North Carolina", 2.565907, 4.259003, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2052, "North Carolina", 0.712514, 4.250259, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2053, "North Carolina", 6.266215, 4.243315, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2055, "North Carolina", 1.258755, 4.133625, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2058, "North Carolina", 5.419383, 4.079224, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2060, "North Carolina", 5.775645, 3.648372, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2062, "North Carolina", 4.407171, 4.028209, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2064, "North Carolina", 7.184008, 3.694169, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2066, "North Carolina", 7.085306, 3.8599, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2067, "North Carolina", 4.521417, 3.654822, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2073, "North Carolina", 3.640294, 3.653968, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2079, "North Carolina", 3.223488, 3.644215, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2080, "North Carolina", 2.70177, 3.629579, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2085, "North Carolina", 5.16419, 3.652756, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2086, "North Carolina", 4.680365, 4.237618, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2087, "North Carolina", 5.351428, 3.651687, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2089, "North Carolina", 1.757303, 3.84375, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2091, "North Carolina", 2.129926, 3.783318, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2093, "North Carolina", 2.793824, 3.973093, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2094, "North Carolina", 1.169959, 4.226867, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1298, "Maryland", 4.607855, -0.321387, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1299, "Maryland", 6.83505, 0.285768, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1300, "Maryland", 6.779853, -0.319371, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1321, "Maryland", 6.963921, 0.117259, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1301, "Maryland", 6.973453, 0.870922, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1302, "Maryland", 7.660369, 0.403416, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1303, "Maryland", 6.364252, -0.318842, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1304, "Maryland", 7.442135, -0.320349, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1305, "Maryland", 6.401194, 0.949855, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1306, "Maryland", 7.339054, 0.952528, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1307, "Maryland", 5.998289, -0.317779, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1308, "Maryland", 4.187763, -0.321145, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1309, "Maryland", 7.105963, -0.319543, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1310, "Maryland", 6.488302, 0.120862, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1311, "Maryland", 7.396889, 0.104329, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1312, "Maryland", 6.14813, 0.140638, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1313, "Maryland", 6.589084, 0.418807, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1314, "Maryland", 7.299214, 0.25524, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1316, "Maryland", 7.616109, 1.458959, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1315, "Maryland", 6.801059, 1.19459, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1317, "Maryland", 7.282955, 0.652192, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1318, "Maryland", 5.311954, -0.320996, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1319, "Maryland", 7.758115, 1.131555, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1320, "Maryland", 8.013585, 1.267555, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2542, "Tennessee", 1.33313, 3.694248, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2545, "Tennessee", -0.312199, 3.581498, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2547, "Tennessee", 0.358587, 4.106398, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2561, "Tennessee", -0.057291, 3.806728, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2562, "Tennessee", 0.50333, 3.809054, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2564, "Tennessee", 0.208318, 3.904649, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2566, "Tennessee", 0.203305, 3.584782, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2569, "Tennessee", 0.386516, 3.589892, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2577, "Tennessee", -0.032563, 4.092546, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2578, "Tennessee", 1.616467, 3.564747, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2579, "Tennessee", -0.596174, 4.099543, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2610, "Tennessee", -0.118862, 4.278617, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2614, "Tennessee", 0.973137, 3.562249, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2618, "Tennessee", 1.060352, 4.007082, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2619, "Tennessee", -0.334337, 3.787667, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 2622, "Tennessee", 0.972846, 3.773808, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1884, "New Jersey", 8.25711, -0.128417, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1886, "New Jersey", 8.260351, -0.528066, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 1895, "New Jersey", 8.117126, -0.410198, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3097, "West Virginia", 3.44824, 0.20395, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3098, "West Virginia", 5.446647, -0.193042, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3099, "West Virginia", 1.695847, 1.54426, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3100, "West Virginia", 2.643738, 0.702306, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3102, "West Virginia", 1.167736, 1.084037, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3103, "West Virginia", 2.397, 0.526127, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3104, "West Virginia", 2.39154, 0.997717, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3105, "West Virginia", 2.761574, 0.018247, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3106, "West Virginia", 2.294584, 1.503123, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3107, "West Virginia", 2.618742, 0.445764, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3108, "West Virginia", 4.18824, 0.17131, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3109, "West Virginia", 2.781534, 1.498348, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3110, "West Virginia", 4.695516, -0.091875, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3112, "West Virginia", 4.541118, 0.285486, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3113, "West Virginia", 3.071112, -0.004483, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3114, "West Virginia", 1.766767, 0.463292, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3115, "West Virginia", 5.639961, -0.041859, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3116, "West Virginia", 1.760218, 1.049482, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3117, "West Virginia", 2.947089, 0.373679, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3118, "West Virginia", 1.369023, 1.361556, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3119, "West Virginia", 1.47852, 1.80082, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3121, "West Virginia", 3.177251, -0.216599, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3122, "West Virginia", 2.80548, -0.70918, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3123, "West Virginia", 1.45385, 0.544918, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3120, "West Virginia", 1.678834, 2.396378, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3124, "West Virginia", 2.313258, 2.335121, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3125, "West Virginia", 4.403135, -0.228093, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3126, "West Virginia", 1.254027, 1.864043, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3127, "West Virginia", 3.254024, -0.319172, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3128, "West Virginia", 2.81694, 2.167895, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3129, "West Virginia", 5.206775, -0.287443, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3130, "West Virginia", 2.443777, 1.135454, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3133, "West Virginia", 2.304142, -0.012297, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3134, "West Virginia", 3.312118, 0.911377, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3135, "West Virginia", 3.775675, -0.319041, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3136, "West Virginia", 1.610851, 0.977348, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3137, "West Virginia", 2.103931, 1.847257, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3138, "West Virginia", 3.395355, 0.434637, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3139, "West Virginia", 2.346187, 0.096117, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3140, "West Virginia", 2.128783, 0.655459, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3141, "West Virginia", 2.580782, 1.996418, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3142, "West Virginia", 3.470378, 0.016934, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3143, "West Virginia", 3.837323, 0.244288, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3144, "West Virginia", 2.553943, -0.176142, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3145, "West Virginia", 3.265872, 0.441526, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3146, "West Virginia", 1.030673, 1.305254, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3147, "West Virginia", 2.997125, 0.908554, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3148, "West Virginia", 2.731632, -0.319238, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3149, "West Virginia", 2.093966, 0.350551, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3150, "West Virginia", 1.919161, 0.069548, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3151, "West Virginia", 1.819473, 2.093502, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 3132, "West Virginia", 4.026337, 0.635629, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 424, "United States", 6.555655, 0.58808, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 421, "Delaware", 7.915107, 0.125445, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 422, "Delaware", 7.886518, -0.466465, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (49, 423, "Delaware", 7.952612, 0.630525, "outside");
