INSERT INTO `map` (`map_id`, `map_scale`, `map_name`, `map_thumbnail`, `map_primary_color_R`, `map_primary_color_G`, `map_primary_color_B`, `map_is_custom`) VALUES (34, 124.207587, 'New Mexico Counties', 'New_Mexico_Counties_Thumbnail.png', 191,10,48, 0);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1924, "New Mexico", 0.003990, 0.000283);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1921, "New Mexico", 1.423637, 0.000116);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1929, "New Mexico", 2.997823, 0.005268);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1904, "New Mexico", 3.672473, 0.004991);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1931, "New Mexico", 5.040832, 0.000000);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1911, "New Mexico", 4.611054, 0.977122);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1925, "New Mexico", 3.328966, 1.411308);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1926, "New Mexico", 2.799674, 1.247390);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1923, "New Mexico", 1.423662, 0.975420);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1915, "New Mexico", 2.631654, 1.283553);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1918, "New Mexico", 3.329645, 0.922612);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1917, "New Mexico", 0.003377, 1.246852);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1903, "New Mexico", 0.004017, 2.064897);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1901, "New Mexico", 0.002703, 3.025502);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1928, "New Mexico", 1.323478, 3.024723);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1932, "New Mexico", 1.845793, 2.553324);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1900, "New Mexico", 1.852929, 2.225966);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1930, "New Mexico", 2.580383, 2.447752);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1910, "New Mexico", 3.737101, 2.229677);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1920, "New Mexico", 4.921029, 1.575894);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1905, "New Mexico", 5.310108, 2.557575);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1922, "New Mexico", 5.101004, 2.993966);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1902, "New Mexico", 3.696163, 3.639781);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1913, "New Mexico", 5.235666, 4.287072);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1908, "New Mexico", 4.198649, 5.043564);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1919, "New Mexico", 2.672909, 4.511950);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1914, "New Mexico", 2.676513, 3.316283);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1906, "New Mexico", 4.156796, 2.776119);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1927, "New Mexico", 1.049571, 4.400039);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1909, "New Mexico", 0.002693, 4.738673);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1916, "New Mexico", 0.820223, 5.493478);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1912, "New Mexico", 0.000000, 5.278048);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (34, 1907, "New Mexico", 1.750542, 4.934317);

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2239, "Oklahoma", 8.095825, -0.002468, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2240, "Oklahoma", 9.049785, 1.864102, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2248, "Oklahoma", 6.047609, 0.00016, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2258, "Oklahoma", 9.046412, 0.508727, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2263, "Oklahoma", 9.16173, 2.354114, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2264, "Oklahoma", 9.049789, 2.462877, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2265, "Oklahoma", 9.046461, -0.001843, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2268, "Oklahoma", 9.205516, 2.675929, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2300, "Oklahoma", 9.049778, 1.234133, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2305, "Oklahoma", 7.017835, 0.002569, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2311, "Oklahoma", 9.59397, 0.000068, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2312, "Oklahoma", 9.44454, 0.225832, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 351, "Colorado", 1.568042, -0.528401, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 352, "Colorado", 5.96407, -0.805063, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 359, "Colorado", 2.3718, -0.504206, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 360, "Colorado", 3.278783, -0.822389, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 382, "Colorado", 0.67087, -0.799893, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 384, "Colorado", 3.895131, -1.02157, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 390, "Colorado", 0.004134, -0.799193, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 1005, "Kansas", 8.942751, -0.593255, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 1009, "Kansas", 9.506985, -0.480081, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 1052, "Kansas", 8.397445, -0.593697, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 1057, "Kansas", 7.007933, -0.486199, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 1080, "Kansas", 7.982067, -0.484433, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 1087, "Kansas", 7.493568, -0.485317, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2629, "Texas", 5.985477, 5.596235, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2633, "Texas", 7.420916, 2.271394, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2636, "Texas", 6.002827, 3.359176, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2639, "Texas", 9.574523, 3.957759, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2644, "Texas", 7.358889, 5.045794, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2650, "Texas", 7.578408, 2.814938, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2657, "Texas", 9.418761, 5.606403, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2660, "Texas", 7.427233, 1.718707, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2662, "Texas", 6.524541, 2.815052, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2665, "Texas", 8.632389, 2.815883, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2667, "Texas", 5.993517, 3.968888, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2668, "Texas", 8.224803, 6.142027, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2669, "Texas", 9.328111, 6.147679, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2671, "Texas", 8.509471, 2.271359, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2675, "Texas", 8.934958, 6.774956, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2678, "Texas", 8.531482, 3.357663, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2679, "Texas", 6.282807, 6.685647, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2681, "Texas", 7.486593, 3.958259, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2682, "Texas", 4.131816, 6.249668, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2683, "Texas", 6.008249, 0.624411, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2685, "Texas", 6.841653, 5.047992, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2686, "Texas", 6.006912, 2.271249, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2690, "Texas", 8.009016, 3.955728, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2692, "Texas", 7.959424, 2.271359, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2695, "Texas", 6.251088, 6.141552, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2698, "Texas", 2.404694, 6.247124, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2703, "Texas", 8.389548, 5.045954, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2704, "Texas", 7.485318, 3.359674, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2705, "Texas", 9.001693, 3.447847, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2710, "Texas", 5.985258, 5.051419, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2712, "Texas", 7.492704, 4.503772, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2714, "Texas", 7.274089, 6.140875, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2717, "Texas", 7.963893, 1.72617, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2722, "Texas", 6.959758, 3.358875, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2723, "Texas", 8.104041, 2.814938, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2725, "Texas", 7.426257, 0.62588, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2726, "Texas", 9.052452, 3.026198, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2730, "Texas", 6.007988, 1.18092, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2731, "Texas", 9.059193, 4.501511, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2733, "Texas", 8.509953, 1.179676, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2737, "Texas", 6.434726, 3.968888, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2741, "Texas", 7.355163, 5.593762, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2742, "Texas", 3.05217, 6.247351, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2744, "Texas", 7.426706, 1.181033, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2745, "Texas", 7.775374, 6.839429, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2754, "Texas", 8.90363, 5.050137, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2759, "Texas", 8.011384, 4.502957, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2762, "Texas", 8.531482, 3.955321, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2765, "Texas", 9.053738, 3.95533, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2767, "Texas", 6.434726, 3.358875, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2775, "Texas", 8.503448, 0.625662, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2778, "Texas", 5.066238, 6.249597, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2779, "Texas", 6.964439, 3.962225, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2780, "Texas", 6.973959, 4.506841, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2786, "Texas", 6.838925, 5.593762, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2781, "Texas", 9.446491, 6.883227, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2792, "Texas", 6.762744, 6.141552, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2795, "Texas", 7.866176, 5.590661, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2798, "Texas", 6.887158, 1.180943, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2800, "Texas", 8.008688, 3.357663, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2804, "Texas", 8.38482, 5.59365, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2806, "Texas", 7.964458, 0.625665, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2807, "Texas", 6.007399, 1.715896, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2812, "Texas", 6.006193, 2.816089, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2813, "Texas", 5.465089, 7.036156, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2815, "Texas", 6.882702, 1.725044, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2818, "Texas", 6.881334, 2.271101, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2819, "Texas", 7.273982, 6.68614, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2822, "Texas", 4.947822, 6.250133, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2824, "Texas", 7.964105, 1.178324, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2827, "Texas", 8.814181, 6.146991, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2835, "Texas", 7.875611, 5.037508, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2836, "Texas", 9.437951, 5.053992, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2838, "Texas", 6.887158, 0.624434, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2843, "Texas", 7.782544, 6.141279, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2844, "Texas", 8.530964, 4.502957, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2846, "Texas", 7.051681, 2.815052, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2848, "Texas", 8.898262, 5.596798, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2850, "Texas", 6.45515, 4.513308, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2851, "Texas", 9.577729, 4.501511, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2853, "Texas", 7.782227, 6.618517, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2858, "Texas", 6.732123, 6.685808, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2865, "Texas", 5.439285, 6.685538, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2869, "Texas", 8.510015, 1.72617, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2871, "Texas", 9.574523, 3.176733, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2875, "Texas", 5.722636, 6.141357, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2878, "Texas", 5.985495, 4.514678, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 200, "Arizona", -0.950509, 0.001107, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 201, "Arizona", -1.410615, 5.715732, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 202, "Arizona", -4.304002, -0.003707, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 203, "Arizona", -2.670555, 3.127719, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 204, "Arizona", -1.407261, 4.184419, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 205, "Arizona", -0.445567, 4.027637, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 207, "Arizona", -4.284885, 3.690083, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 208, "Arizona", -5.705445, -0.000652, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 209, "Arizona", -1.700525, -0.005036, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 210, "Arizona", -4.283721, 5.607795, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 211, "Arizona", -3.153451, 4.417767, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 212, "Arizona", -2.316749, 6.585669, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 213, "Arizona", -4.284185, 1.836608, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2894, "Utah", -3.851114, -0.679325, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (34, 2900, "Utah", -2.291299, -1.874746, "outside");
