INSERT INTO `map` (`map_id`, `map_scale`, `map_name`, `map_thumbnail`, `map_primary_color_R`, `map_primary_color_G`, `map_primary_color_B`, `map_is_custom`) VALUES (15, 100.383732, 'Idaho Counties', 'Idaho_Counties_Thumbnail.png', 239,0,57, 0);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 666, "Idaho", 0.210642, 0.000000);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 664, "Idaho", 0.200763, 0.192180);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 683, "Idaho", 0.200370, 1.262063);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 660, "Idaho", 0.202958, 1.983064);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 695, "Idaho", 0.913426, 1.165320);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 684, "Idaho", 0.203199, 2.338324);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 690, "Idaho", 0.180242, 2.964320);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 686, "Idaho", 0.529531, 3.165905);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 680, "Idaho", 0.448572, 2.915375);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 673, "Idaho", 0.786929, 2.583096);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 692, "Idaho", 0.216026, 6.650428);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 675, "Idaho", 0.976374, 6.127975);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 656, "Idaho", 0.729603, 6.492226);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 669, "Idaho", 0.210146, 6.401240);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 678, "Idaho", 0.530355, 5.613369);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 693, "Idaho", 0.263353, 6.060686);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 699, "Idaho", 0.000000, 5.199513);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 657, "Idaho", 0.341999, 4.666593);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 698, "Idaho", 1.029156, 4.727186);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 663, "Idaho", 0.961008, 5.814864);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 679, "Idaho", 2.156175, 7.253501);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 687, "Idaho", 2.648422, 7.251704);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 682, "Idaho", 2.625626, 7.687806);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 697, "Idaho", 2.204870, 7.607776);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 671, "Idaho", 2.957579, 7.891885);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 694, "Idaho", 3.999307, 7.362750);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 691, "Idaho", 4.242987, 8.122614);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 658, "Idaho", 4.492465, 7.473477);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 676, "Idaho", 5.116833, 8.213139);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 659, "Idaho", 5.608148, 7.998361);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 670, "Idaho", 5.095611, 7.473452);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 662, "Idaho", 2.246341, 6.260246);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 689, "Idaho", 3.311039, 7.251609);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 668, "Idaho", 2.156872, 6.428229);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 674, "Idaho", 1.938763, 5.152725);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 667, "Idaho", 3.444586, 5.958775);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 661, "Idaho", 4.235267, 6.718154);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 665, "Idaho", 4.723003, 6.717888);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 681, "Idaho", 4.545905, 6.178352);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 688, "Idaho", 5.260391, 6.338893);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 696, "Idaho", 5.842221, 6.271049);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 677, "Idaho", 5.086657, 5.307810);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 672, "Idaho", 4.247936, 5.539825);
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`) VALUES (15, 685, "Idaho", 2.425524, 4.121015);

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3058, "Washington", -2.126402, 2.174296, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3059, "Washington", -0.236961, 3.173626, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3060, "Washington", -2.631454, 2.841824, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3061, "Washington", -3.937749, 0.566837, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3063, "Washington", -5.552936, 3.676892, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3064, "Washington", -0.999491, 2.970595, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3065, "Washington", -5.974923, 3.266379, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3066, "Washington", -3.074356, 1.063239, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3067, "Washington", -1.626606, 0.000924, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3068, "Washington", -2.214432, 2.827891, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3069, "Washington", -0.62032, 2.87319, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3070, "Washington", -2.799839, 1.298901, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3072, "Washington", -5.527018, 0.736976, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3074, "Washington", -5.285102, 1.525712, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3076, "Washington", -4.222949, 1.754822, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3077, "Washington", -4.369475, 3.695934, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3078, "Washington", -6.129679, 2.759546, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3079, "Washington", -1.73675, 1.30405, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3081, "Washington", -3.642613, 0.000551, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3083, "Washington", -0.386394, 0.000977, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3084, "Washington", -5.600262, 1.99696, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3086, "Washington", -5.496871, 0.430179, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3087, "Washington", -5.006825, 3.26565, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3088, "Washington", -5.162522, 0.878341, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3089, "Washington", -0.580602, 1.191601, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3090, "Washington", -1.15918, 0.000379, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3091, "Washington", -5.960074, 2.264313, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3093, "Washington", -1.798471, 2.992918, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3094, "Washington", -5.847519, -0.001685, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3095, "Washington", -1.006095, 2.175722, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3096, "Washington", -4.280043, 2.390495, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 314, "California", -4.214186, 8.754418, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 336, "California", -6.47577, 8.739535, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3224, "Wyoming", 10.920142, 8.209887, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3225, "Wyoming", 8.621712, 4.999476, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3226, "Wyoming", 11.218213, 5.000256, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3227, "Wyoming", 9.313147, 8.208487, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3228, "Wyoming", 11.164891, 6.876882, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3230, "Wyoming", 7.189394, 6.241252, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3232, "Wyoming", 7.930079, 6.151732, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3233, "Wyoming", 9.873406, 5.546456, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3235, "Wyoming", 6.195919, 7.106483, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3236, "Wyoming", 9.699501, 6.87473, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3238, "Wyoming", 6.18614, 4.994052, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3240, "Wyoming", 9.331506, 4.999582, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3241, "Wyoming", 6.61955, 6.920454, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3242, "Wyoming", 7.188618, 8.413002, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3243, "Wyoming", 6.187694, 5.41803, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 3245, "Wyoming", 8.692269, 6.040864, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2313, "Oregon", -1.27594, 4.90072, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2315, "Oregon", -5.625046, 4.424339, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2319, "Oregon", -3.86551, 5.546421, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2321, "Oregon", -4.759335, 5.759699, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2322, "Oregon", -6.97568, 6.320706, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2323, "Oregon", -3.410507, 3.98583, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2324, "Oregon", -2.429201, 5.006131, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2325, "Oregon", -2.700752, 6.191647, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2326, "Oregon", -4.679024, 4.093256, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2327, "Oregon", -5.988081, 7.505643, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2328, "Oregon", -4.606485, 5.214034, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2330, "Oregon", -5.046945, 6.730626, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2331, "Oregon", -4.106652, 6.729752, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2332, "Oregon", -6.915619, 5.888261, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2334, "Oregon", -6.017712, 5.259915, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2335, "Oregon", -0.989187, 5.695716, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2336, "Oregon", -5.937049, 4.646582, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2337, "Oregon", -2.763528, 3.844613, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2338, "Oregon", -5.686119, 4.090712, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2340, "Oregon", -3.786576, 4.079872, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2342, "Oregon", -2.191761, 3.75019, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2343, "Oregon", -1.454739, 3.925092, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2344, "Oregon", -0.734636, 3.750528, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2345, "Oregon", -4.562242, 4.120246, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2347, "Oregon", -3.252133, 4.916084, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2883, "Utah", 3.200474, 8.749911, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2884, "Utah", 5.07828, 8.752036, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 2898, "Utah", 5.731231, 8.749474, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1703, "Montana", 3.304706, 3.827915, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1704, "Montana", 8.543451, 3.69692, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1705, "Montana", 7.691269, 0.001067, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1706, "Montana", 5.455078, 2.774117, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1707, "Montana", 7.444354, 4.203134, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1709, "Montana", 5.195246, 1.62801, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1710, "Montana", 5.833931, 0.868334, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1711, "Montana", 11.051292, 2.675408, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1712, "Montana", 11.091096, 0.001808, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1714, "Montana", 3.725618, 3.4179, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1716, "Montana", 7.029431, 1.497534, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1717, "Montana", 2.222948, 0.000085, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1718, "Montana", 5.437647, 3.51039, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1719, "Montana", 9.276152, 1.272857, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1720, "Montana", 3.174847, 0.002861, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1721, "Montana", 7.589157, 2.812244, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1722, "Montana", 3.364669, 2.711185, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1723, "Montana", 6.487154, 0.001068, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1724, "Montana", 4.645091, 3.03959, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1725, "Montana", 6.454725, 1.980611, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1726, "Montana", 2.638171, 1.186557, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1727, "Montana", 4.077216, 1.309035, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1728, "Montana", 5.833931, 0.003175, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1729, "Montana", 1.193133, 0.000142, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1731, "Montana", 4.538179, 3.927956, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1730, "Montana", 10.813157, 1.130121, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1732, "Montana", 5.584895, 2.391442, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1733, "Montana", 1.483807, 1.88217, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1734, "Montana", 2.445823, 1.751361, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1735, "Montana", 8.233045, 2.806589, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1736, "Montana", 6.196418, 3.510559, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1737, "Montana", 8.506189, 1.753565, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1738, "Montana", 8.351912, 0.0012, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1739, "Montana", 3.893981, 0.646915, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1740, "Montana", 10.963318, 4.015682, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1741, "Montana", 3.776543, 1.751231, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1742, "Montana", 11.156251, 2.274454, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1743, "Montana", 2.676964, 2.925312, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1746, "Montana", 9.345672, 2.676929, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1747, "Montana", 1.19336, 0.92234, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1749, "Montana", 4.15751, 3.520122, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1750, "Montana", 7.178446, 3.585969, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1751, "Montana", 6.950275, 3.475676, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1752, "Montana", 4.228216, 1.084963, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1753, "Montana", 5.049617, 0.003176, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1754, "Montana", 9.50448, 3.148041, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1755, "Montana", 9.828142, 0.001304, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1756, "Montana", 6.961056, 2.810296, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1758, "Montana", 8.317655, 3.131379, "outside");

INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1855, "Nevada", 0.224608, 8.748674, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1858, "Nevada", -2.088041, 8.750957, "outside");
INSERT INTO `mapRegion` (`mapRegion_map_id`, `mapRegion_region_id`, `mapRegion_parent`, `mapRegion_offsetX`, `mapRegion_offsetY`, `mapRegion_type`) VALUES (15, 1866, "Nevada", -2.762719, 8.754503, "outside");
